# Generated by Django 2.0.3 on 2018-09-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180925_1813'),
        ('custumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolatepreference',
            name='chocolate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.ChocolateType', verbose_name='Chocolate Type'),
        ),
        migrations.AlterField(
            model_name='fruitpreference',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.Fruit', verbose_name='Fruit'),
        ),
        migrations.DeleteModel(
            name='ChocolateType',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
