# Generated by Django 2.0.3 on 2018-09-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0002_auto_20180925_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custumer.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
