# Generated by Django 2.0.3 on 2018-09-26 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='ZipCode')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('state', models.CharField(max_length=250, verbose_name='State')),
                ('country', models.CharField(max_length=250, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='ChocolatePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='Preference level')),
                ('chocolate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.ChocolateType', verbose_name='Chocolate Type')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulling_day', models.IntegerField(verbose_name='Bulling Day')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Last Name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='FruitPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='Preference level')),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Customer', verbose_name='Customer')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box.Fruit', verbose_name='Fruit')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.Subscription', verbose_name='Subscription'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.Subscription', verbose_name='Subscription'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='chocolatepreference',
            name='custumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Customer', verbose_name='Customer'),
        ),
    ]
