# Generated by Django 2.0.3 on 2018-09-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Total Value')),
                ('payday', models.DateField(blank=True, null=True, verbose_name='Payday')),
                ('discount', models.FloatField(verbose_name='Total Value')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('chocolate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custumer.ChocolateType', verbose_name='Chocolate type')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custumer.Fruit', verbose_name='Fruit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.IntegerField(verbose_name='Bulling Day')),
                ('order_number', models.CharField(max_length=100, verbose_name='Order Number')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Bill', verbose_name='Bill')),
                ('custumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custumer.Custumer', verbose_name='Bill')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='chocolate',
            field=models.ManyToManyField(blank=True, to='order.Chocolate'),
        ),
    ]
