# Generated by Django 2.0.3 on 2018-09-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Total Value')),
                ('payday', models.DateField(blank=True, null=True, verbose_name='Payday')),
                ('discount', models.FloatField(verbose_name='Total Value')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.IntegerField(verbose_name='Bulling Day')),
                ('order_number', models.CharField(max_length=100, verbose_name='Order Number')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Bill', verbose_name='Bill')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.Customer', verbose_name='Bill')),
            ],
        ),
    ]
